### ISSUE TITLE
AttributeError: 'int' object has no attribute 'predict'

### ISSUE THREAD

**Issue by maheerb** [cjekel/tindetheus#16]
Traceback (most recent call last): File "c:\users\focus\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "c:\users\focus\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\Focus\Anaconda3\envs\tensorflow\Scripts\tindetheus.exe\__main__.py", line 9, in <module> File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\tindetheus.py", line 781, in command_line_run main(args, defaults['facebook_token'], defaults['XAuthToken']) File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\tindetheus.py", line 644, in main my_sess.like() File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\tindetheus.py", line 560, in like self.like_or_dislike_users(users) File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\tindetheus.py", line 489, in like_or_dislike_users yhat = self.model.predict(X) AttributeError: 'int' object has no attribute 'predict'

Hey @cjekel, I am not sure what to do here. All the other errors that came up so far, I have managed to debug. But stuck on this error. Any insights on how to solve this error? Thanks!

**Comment by cjekel** [comment]
What's the final output when you run ```tindetheus train```?

You should see something like
```
Summary statistics of profiles with at least one detectable face
count    164.000000
mean       5.213415
std        2.041788
min        1.000000
25%        4.000000
50%        5.000000
75%        7.000000
max        9.000000
dtype: float64
Train size:  164
Training accuracy 0.7439024390243902
Recall/ Like accuracy 0.8051948051948052
specificity/ Dislike accuracy 0.6896551724137931
```

Then if you open the pickled model
```python
import joblib
model = joblib.load('log_reg_model.pkl') 
print(model)
```

You should see something like this

```
LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)
```

**Comment by maheerb** [comment]
```
Total number of images: 918
Number of successfully aligned images: 802
Model directory: 20170512-110547
Metagraph file: model-20170512-110547.meta
Checkpoint file: model-20170512-110547.ckpt-250000
WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
Number of images:  802
Number of batches:  1
Completed batch 1 of 1
Run time:  132.94302654266357
Summary statistics of profiles with at least one detectable face
count    154.000000
mean       5.207792
std        2.168326
min        1.000000
25%        4.000000
50%        5.000000
75%        7.000000
max        9.000000
dtype: float64
c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
Train size:  154
Training accuracy 0.7922077922077922
Recall/ Like accuracy 0.782608695652174
specificity/ Dislike accuracy 0.7962962962962963
```
tried to import the joblib but
 ```
(tensorflow) C:\Users\Focus\tinder>import joblib
'import' is not recognized as an internal or external command,
operable program or batch file.
```
Please advise what to do. I am new at python and this is first major project. Thanks!

**Comment by cjekel** [comment]
Hmm... it looks like the model is working.

Do you get the same error when you run ```tindetheus like``` now?

**Comment by maheerb** [comment]
Actually I am getting this error now if i do tindetheus browse or tindetheus like. I tried to fix this too via this solution: https://github.com/charliewolf/pynder/issues/193 but no avail.
```
main(args, defaults['facebook_token'], defaults['XAuthToken'])
  File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\tindetheus.py", line 126, in main
    x_auth_token=x_auth_token)
  File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\tinder_client.py", line 89, in __init__
    self.session = self.login(facebook_token, x_auth_token)
  File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\tinder_client.py", line 128, in login
    print('Hello ', session.profile)
  File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\pynder\session.py", line 22, in profile
    return Profile(self._api.profile(), self._api)
  File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\pynder\api.py", line 87, in profile
    return self._get("/profile")
  File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\pynder\api.py", line 52, in _get
    return self._request("get", url)
  File "c:\users\focus\anaconda3\envs\tensorflow\lib\site-packages\pynder\api.py", line 46, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 400
```

**Comment by cjekel** [comment]
How are you logging in? If you use sms you may need to resubmit a token.

**Comment by maheerb** [comment]
I am logging in through XAuthToken. It was working fine so far. Not sure.
Its a login issue right now no?

**Comment by cjekel** [comment]
XAuthToken expires after sometime (perhaps 24 hours). Try to grab a new XAuthToken.
