### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by Rahov** [cjekel/tindetheus#17]
### Issue:

I've recently installed tindetheus on my machine alongside all the dependencies, however, I've been getting this JSON Decode Error and have not been able to make any progress since. From my understanding, this could be an issue either with tinder's API or my access token. The config I have set up contains only the facebook token which was obtained by the following method:

https://gist.github.com/taseppa/66fc7239c66ef285ecb28b400b556938

## Output from tindetheus

```bash
tindetheus browse

Traceback (most recent call last):
  File "/home/rahov/.conda/envs/tensorflow/bin/tindetheus", line 8, in <module>
    sys.exit(command_line_run())
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 268, in command_line_run
    main(args, defaults['facebook_token'], defaults['XAuthToken'])
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 62, in main
    likes_left=args.likes, x_auth_token=x_auth_token)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tinder_client.py", line 89, in __init__
    self.session = self.login(facebook_token, x_auth_token)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tinder_client.py", line 127, in login
    XAuthToken=x_auth_token)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/pynder/session.py", line 18, in __init__
    self._api.auth(facebook_id, facebook_token)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/pynder/api.py", line 28, in auth
    self._full_url('/auth'), json=data, proxies=self._proxies).json()
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cjekel** [comment]
This is a good sign if you have gotten this far.

I believe this is a pynder issue. 

Did you install this PR of pynder?
```shell
```

**Comment by Rahov** [comment]
Thank you for the quick reply. That indeed worked, however, I'm still getting errors. This time its a authentication issue.

bash```
pynder.errors.RequestError: Couldn't authenticate request status code: 401
```

From what I've been reading, this might require me to test a new account and see if facebook has blocked the token, although I can still access the account with the current token.

**Comment by cjekel** [comment]
I would troubleshoot things by seeing if you can get a session in pynder going first

```python
import pynder
X_Auth_Token = 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'
session = pynder.Session(XAuthToken=X_Auth_Token)
print(session.profile)
```
or
```python
facebook_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
session = pynder.Session(facebook_auth_token=facebook_token)
print(session.profile)
```

**Comment by Rahov** [comment]
I've tried to import pynder with the version that uses Facebook but the list index is out of range.

As requested, the output I'm getting after changing to lower config:

```bash
Traceback (most recent call last):
  File "/home/rahov/.conda/envs/tensorflow/bin/tindetheus", line 8, in <module>
    sys.exit(command_line_run())
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 268, in command_line_run
    main(args, defaults['facebook_token'], defaults['XAuthToken'])
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 62, in main
    likes_left=args.likes, x_auth_token=x_auth_token)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tinder_client.py", line 89, in __init__
    self.session = self.login(facebook_token, x_auth_token)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tinder_client.py", line 127, in login
    XAuthToken=x_auth_token)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/pynder/session.py", line 18, in __init__
    self._api.auth(facebook_id, facebook_token)
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/pynder/api.py", line 41, in auth
    raise errors.RequestError(err)
pynder.errors.RequestError: Couldn't authenticate request status code: 401
```

**Comment by cjekel** [comment]
What's the format of your token? 

Is it like this:
```python
'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'
```
or
```python
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
# I don't actually know how long this will be
```

See also https://github.com/cjekel/tindetheus/issues/11#issuecomment-505923088

**Comment by Rahov** [comment]
Sorry for the delay.

Its:
```'xxxxxxxxxxxxxxxxx```

**Comment by cjekel** [comment]
> I've tried to import pynder with the version that uses Facebook but the list index is out of range.

You got a list index out of range when running this?
```python
import pynder
facebook_token = 'xxxxxxxx'
# where 'xxxxxxxx' is your facebook token
session = pynder.Session(facebook_token=facebook_token)
print(session.profile)
```

My config.txt parser is dumb, and could have bugs. Make sure the line that says facebook_token within config.txt looks just like this ```facebook_token = XXXXXXX  # your facebook token hash```, where there are no quotes, and you leave the space and comment after the token.

**Comment by Rahov** [comment]
> My config.txt parser is dumb, and could have bugs. Make sure the line that says facebook_token within config.txt looks just like this facebook_token = XXXXXXX # your facebook token hash, where there are no quotes, and you leave the space and comment after the token.

That is exactly how I've been doing it up to now. However, I do still get:

```bash
Traceback (most recent call last):                                                                             1 ↵
  File "/home/rahov/.conda/envs/tensorflow/bin/tindetheus", line 8, in <module>
    sys.exit(command_line_run())
  File "/home/rahov/.conda/envs/tensorflow/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 250, in command_line_run
    defaults[my_line_list[0]] = my_line_list[2].strip('\n')
IndexError: list index out of range
```

> See also #11 (comment)

I've attempted phone authentication script, but it fails to establish a connection.

```bash
requests.exceptions.ConnectionError: 
HTTPSConnectionPool(host='graph.accountkit.com', port=443): Max retries exceeded with url: 
/v1.2/start_login?access_token=AA%7C464891386855067%7Cd1891abb4b0bcdfa0580d9b839f4a522&credentials_type=phone_number&fb_app_events_enabled=1&fields=privacy_policy%2Cterms_of_service&locale=fr_FR&phone_number=XXXXXXXXXXXX&response_type=token&sdk=ios 
(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f343a91fa50>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Just wanted to let you know: I will not have access to my PC this work week so I won't be able to continue giving information on the issue up to Saturday.

**Comment by cjekel** [comment]
https://github.com/cjekel/tindetheus/commit/07bd505d37a7de11496321afa4e7371c83f07c7b fixes the issue you were having with ```IndexError: list index out of range```

Please let me know if the line that was not being read in the config.txt is important for your application. This new version will print the line that is not being read.

update to version 0.5.1 with pip by running
```
pip install tindetheus --upgrade --no-deps
```

As far as logging in with a token, I think the easiest way is to open an IPython shell, and keep trying combinations like
```python
import pynder
facebook_token = 'xxxxxxxx'
# where 'xxxxxxxx' is your facebook token
session = pynder.Session(facebook_token=facebook_token)
print(session.profile)
```
If you are able to print profile then you have a valid token and can log in. I know some methods with tokens expire. Logging out will affect this token.

**Comment by cjekel** [comment]
FYI, the way you are fetching the token, the token may only be valid for ~1 hour.

**Comment by Rahov** [comment]
Hey, thanks for your time and help. I've not managed to get it working but that's fine, I'll try to do something else.
