### ISSUE TITLE
Keeps crashing during tindetheus like and/or browse

### ISSUE THREAD

**Issue by holdenjrussell** [cjekel/tindetheus#18]
Here's the error code
Traceback (most recent call last):
  File "/opt/anaconda3/bin/tindetheus", line 10, in <module>
    sys.exit(command_line_run())
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 274, in command_line_run
    main(args, defaults['facebook_token'], defaults['XAuthToken'])
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 63, in main
    my_sess.browse()
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/tinder_client.py", line 286, in browse
    self.look_at_users(users)
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/tinder_client.py", line 145, in look_at_users
    image_list = imgproc.download_url_photos(urls, user.id)
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/image_processing.py", line 70, in download_url_photos
    urlretrieve(url, image_list[-1])
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by cjekel** [comment]
Does this happen on certain profiles or every profile?  I seem to remember to see this on <1% of profiles, which makes me think that it's and advertisement that isn't being correctly accessed by pynder.

I wonder if it's possible to keep the session open, wait for a few minutes, then look for new users to avoid this. Or if it's better to close the session, wait for a few minutes, and open another one. Either way, better exception handling in tindetheus could avoid this issue.

**Comment by holdenjrussell** [comment]
I usually can start it up right again after, so if we could have it wait a few minutes and try again I think that would be a good resolution. Like you mentioned, finding a way to keep the session open would be beneficial. 

It happens after it browses a couple hundred profiles. 

The last time it popped up was after about 1000 profiles. Then it kept popping up every 100 profiles or so.

**Comment by cjekel** [comment]
I would guess that advertisements are messing things up.

https://github.com/cjekel/tindetheus/commit/3e7aad532e3703e5b2743f42ec4b0621e37955de 

I added a config setting for retries when running tindetheus like. I figure that's where this issue is more annoying. It will close the session and reopen a new one. The default is 20, but you can set it in config.txt as
```
retries = 25
```

Feel free to give it a test in the meantime. I'm recording a session now to see if it works.

**Comment by cjekel** [comment]
Looks like it's working
```
HTTP Error 403: Forbidden
Closing session.
Let's try again.
 Retries left: 9
```

**Comment by holdenjrussell** [comment]
I'm running a test now. I'll keep you posted!

**Comment by cjekel** [comment]
I ended up pushing this to pypi as a new release, so thanks for making an issue. I think this will be a nice fix for those using this.

I'm not sure what is causing the 403. At some point it looks like it comes up when there are no free likes remaining on the account a 403 is raised.

**Comment by holdenjrussell** [comment]
Thanks for sharing your code! It works REALLY well. I ended up creating a database by compiling folders of pictures I found attractive/non attractive and used those to train with. It’s showing an accuracy of .89 with about 1800 photos in the like folder and 1500 in the dislike folder. I only manually browsed about 30 profiles.

**Comment by holdenjrussell** [comment]
Getting this error now
Traceback (most recent call last):
  File "/opt/anaconda3/bin/tindetheus", line 10, in <module>
    sys.exit(command_line_run())
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 288, in command_line_run
    retries=defaults['retries'])
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/tindetheus.py", line 134, in main
    my_sess.like()
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/tinder_client.py", line 314, in like
    self.like_or_dislike_users(users)
  File "/opt/anaconda3/lib/python3.7/site-packages/tindetheus/tinder_client.py", line 272, in like_or_dislike_users
    print(user.dislike())
  File "/opt/anaconda3/lib/python3.7/site-packages/pynder/models/user.py", line 116, in dislike
    return self._session._api.dislike(self.id)
  File "/opt/anaconda3/lib/python3.7/site-packages/pynder/api.py", line 104, in dislike
    return self._get("/pass/{}".format(user))
  File "/opt/anaconda3/lib/python3.7/site-packages/pynder/api.py", line 60, in _get
    return self._request("get", url)
  File "/opt/anaconda3/lib/python3.7/site-packages/pynder/api.py", line 54, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 401

**Comment by cjekel** [comment]
@holdenjrussell the ``` pynder.errors.RequestError: 401``` errors are typically authentication issues with Pynder. Sometimes the api has gone down, or it's also possible if you grabbed a temporary token that it is expired.

**Comment by cjekel** [comment]
Is this issue ready to be closed?
