### ISSUE TITLE
Installing on Windows issue

### ISSUE THREAD

**Issue by mkaizen** [cjekel/tindetheus#23]
Hi, I'm sorry if this is a dumb error but I just followed your article on installing Tindetheus on Windows 10 and instead of getting prompted for a config file I got these errors and was wondering if you had any idea what they mean? I've tried googling and am not getting very far. Thank you for your time, very excited to try out Tindetheus. 

2019-12-15 17:39:24.588753: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2019-12-15 17:39:24.591269: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Matthew\Anaconda3\envs\tensorflow\Scripts\tindetheus.exe\__main__.py", line 5, in <module>
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\__init__.py", line 1, in <module>
    from .tindetheus import *  # noqa F401
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tindetheus\tindetheus.py", line 34, in <module>
    import tensorflow as tf
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1005, in _handle_fromlist
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\core\framework\node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "c:\users\matthew\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\core\framework\tensor_shape_pb2.py", line 112, in <module>
    '__module__' : 'tensorflow.core.framework.tensor_shape_pb2'
TypeError: expected bytes, Descriptor found

**Comment by cjekel** [comment]
See if you can make a new conda environment following these instructions https://github.com/cjekel/tindetheus/issues/20#issuecomment-565835806

What version of tensorflow is this?

**Comment by mkaizen** [comment]
I believe its 1.15.0 from "pip show tensorflow" on cmd. I tried your instructions and it worked! Thank you so much.

**Comment by mkaizen** [comment]
Whoops spoke to soon I got to the prompt for the config file, made the config file/added my x-auth token and now when I run it I get this in the Anaconda cmd upon running "tindetheus train" 

(py36) C:\Users\Matthew\Desktop\Tinder>tindetheus train
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
OMP: Info #156: KMP_AFFINITY: 8 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 4 cores/pkg x 2 threads/core (4 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 0 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 1 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 1 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 2 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 2 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 3 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 3 thread 1
OMP: Info #250: KMP_AFFINITY: pid 14988 tid 20372 thread 0 bound to OS proc set 0
Traceback (most recent call last):
  File "c:\users\matthew\anaconda3\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\matthew\anaconda3\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Matthew\Anaconda3\envs\py36\Scripts\tindetheus.exe\__main__.py", line 7, in <module>
  File "c:\users\matthew\anaconda3\envs\py36\lib\site-packages\tindetheus\tindetheus.py", line 299, in command_line_run
    retries=defaults['retries'])
  File "c:\users\matthew\anaconda3\envs\py36\lib\site-packages\tindetheus\tindetheus.py", line 88, in main
    tindetheus_align.main()
  File "c:\users\matthew\anaconda3\envs\py36\lib\site-packages\tindetheus\tindetheus_align.py", line 81, in main
    dataset = facenet.get_dataset(input_dir)
  File "c:\users\matthew\anaconda3\envs\py36\lib\site-packages\tindetheus\facenet_clone\facenet.py", line 320, in get_dataset
    classes = [path for path in os.listdir(path_exp) \
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'database'

is this just a simple path correcting issue?

**Comment by cjekel** [comment]
Did you browse a few profiles first? You need a like and dislike before train will run.

**Comment by mkaizen** [comment]
Wow, my bad nope just did it now  and its running perfectly. Thanks a ton!
