### ISSUE TITLE
tindetheus browse - pynder.errors.RequestError: 500

### ISSUE THREAD

**Issue by lboc80** [cjekel/tindetheus#55]
running `tindetheus browse`.
I receive a 500 error from the tinder client after a successfull login:

```
Traceback (most recent call last):
  File "/usr/local/bin/tindetheus", line 33, in <module>
    sys.exit(load_entry_point('tindetheus', 'console_scripts', 'tindetheus')())
  File "/tindetheus/tindetheus/tindetheus.py", line 278, in command_line_run
    main(args, defaults['facebook_token'], defaults['XAuthToken'],
  File "/tindetheus/tindetheus/tindetheus.py", line 80, in main
    likes_left=args.likes, x_auth_token=x_auth_token)
  File "/tindetheus/tindetheus/tinder_client.py", line 95, in __init__
    self.session.profile.distance_filter = self.search_distance
  File "/usr/local/lib/python3.6/dist-packages/pynder/models/me.py", line 32, in __set__
    instance.__init__(instance._api.update_profile(profile), instance._api)
  File "/usr/local/lib/python3.6/dist-packages/pynder/api.py", line 98, in update_profile
    return self._post("/profile", profile)
  File "/usr/local/lib/python3.6/dist-packages/pynder/api.py", line 63, in _post
    return self._request("post", url, data=data)
  File "/usr/local/lib/python3.6/dist-packages/pynder/api.py", line 54, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 500
```

**Comment by cjekel** [comment]
The 500 error could be a lot of things. I haven't been following the tinder api, and it's possible the api has changed.

What I would do in your case is manually open a Pynder session and see what you have access to. You're going to have to try a few things to troubleshoot this.

```python
import pynder
session = pynder.Session(facebook_token, X_auth_token) # w/e you use to login
print(session.profile)
# change distance
session.profile.distance_filter = 5
```
from https://github.com/cjekel/tindetheus/issues/12

Also check if you can get nearby users `users = session.nearby_users() # returns a iterable of users nearby`

It seems that this user https://github.com/charliewolf/pynder/issues/218 reported a 500 when the distance filter is changed. The code here will change the distance filter immediately after login, which could be the issue here.
